### ISSUE TITLE
[Feature] Add support for Shodan DNS DB lookup

### ISSUE THREAD

**Issue by ZeroDot1** [Findomain/Findomain#111]
The API is documented on the Shodan developer website: https://developer.shodan.io/api
You can quickly test it using the URL:

https://api.shodan.io/dns/domain/github.com?key=YOUR_API_KEY

**Comment by Edu4rdSHL** [comment]
Hello, thanks. It's in the roadmap but I haven't done it because:

1) I have already an account with my only Gmail address in shodan but I got `{"error": "Insufficient query credits, please upgrade your API plan or wait for the monthly limit to reset"}` still when i have never used it.
2) Shodan doesn't accept my Protonmail email to register in the service, they keep sucking at "Invalid email address."

If you can provide an shodan API key for testing I will add this source, you know how to reach me!

**Comment by ZeroDot1** [comment]
I just tried it with a completely new account and got the same result. :(
I'll e-mail Shodan and let you know if I get a response.

**Comment by ZeroDot1** [comment]
I close this here because I have not received any response.
