### ISSUE TITLE
fatal: Remote branch develop not found in upstream origin

### ISSUE THREAD

**Issue by shadowzoom** [Findomain/Findomain#128]
git clone https://github.com/Edu4rdSHL/findomain.git -b develop
Cloning into 'findomain'...
fatal: Remote branch develop not found in upstream origin

**Comment by Edu4rdSHL** [comment]
Hello, thank you for reporting it. The `develop` branch was removed because it doesn't makes sense actually, new features for Findomain public versions are taken from our Findomain Plus private version and have already been tested, so there is not a "testing" process. I'm going to remove that part of the docs.

I hope that you understand.

Regards,
Ed
